/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Click on a button to start researching!": "点击一个按钮开始研究！",
    "Intro": "介绍",
    "Let's get started...": "让我们开始吧...",
    "OK!": "好的!",
    "Physics": "物理学",
    "Research": "研究",
    "The year is 1984. You are Lennox, a physicist researching the most cutting-edge technology: Quantum Computing! With enough research, you should be able to build your own Quantum Computer.": "这一年是 1984 年。你是 Lennox，一位研究最前沿技术：量子计算 的物理学家！ 通过足够的研究，您应该能够构建自己的量子计算机。",
    "About": "关于",
    "Light Mode": "浅色模式",
    "Restart": "重新开始",
    "Version History": "更新日志",
    "Cancel": "取消",
    "copy export to clipboard": "复制存档到剪切板",
    "Dark Mode": "深色模式",
    "Copy to Clipboard": "复制到剪切板",
    "Done!": "完成!",
    "Export Game": "导出存档",
    "Back to it!": "返回！",
    "author page": "作者页面",
    "made for the new year's incremental game jam (2022)": "为新年的增量游戏 jam 制作(2022)",
    "Neat": "关闭",
    "Pause": "暂停",
    "Paused": "已暂停",
    "special thanks to": "特别的感谢给",
    "There was time now... to go to the bathroom.": "时间到了……去洗手间了。",
    "this is a game about \"science\" and \"time\"": "这是一个关于“科学”和“时间”的游戏",
    "writing by James Funfer": "作者是 James Funfer",
    "I'm going back to the start": "我要回到起点",
    "Oops, never mind": "喔，没关系",
    "Restart Game?": "重新开始游戏？",
    "You will lose all of your progress!": "你将失去所有的游戏进度！建议先导出、备份存档~",
    "...how?": "...如何？",
    "...let's not overthink this. Just carry on with your research and forward me the data.": "...我们不要想太多。 继续你的研究并将数据转发给我。",
    "A Breakthrough.": "一个突破。",
    "Eureka! If I reroute the nanoseconds through the quantum flux thingamajig in the compumatrix, I *should* be able to slow time down. If only I had some undergrads to help, this is a lot of work and I haven't even had time to order a pizza - the most important element of research!": "尤里卡！ 如果我通过计算矩阵中的量子通量 thingamajig 重新路由纳秒，我*应该*能够减慢时间。 如果我有一些本科生可以帮忙，这是很多工作，我什至没有时间点一份披萨——这是研究中最重要的元素！",
    "Yes you are! In approximately three days you will lose most of your funding. But you must carry on! I am you from the future and I come with a dire warning... a quantum doomsday event is coming and I need your assistance to stop it... will you help me?": "是的，你是！ 在大约三天内，您将失去大部分资金。 但你必须继续！ 我是来自未来的你，我带着可怕的警告而来……量子世界末日事件即将来临，我需要你的帮助来阻止它……你能帮帮我吗？",
    "Yessirma'am, it is indeed an ordinary type day in the ordinary present in which I do my EXTRAORDINARY RESEARCH. It sure is quiet and lonely doing research of the singularly unique type to which I am accustomed to doing. Maybe the radio will help motivate me to greater heights of genius...": "Yessirma'am，这确实是一个平凡的日子，我做我的非凡研究。 做我习惯做的独特类型的研究肯定是安静而孤独的。 也许收音机会帮助激励我达到更高的天才高度……",
    "And it was at that time that Lennox experienced a *flashback*": "正是在那个时候，Lennox经历了一次*闪回*",
    "And then, as Young Lennox fiddled with the radio dial...": "然后，当年轻的Lennox摆弄收音机拨号时……",
    "As completely improbable, fantastical, and downright impossible as this all sounds... yes, I will help you... me. But if I continue my research, won't that change the trajectory of my future?": "就像这一切听起来一样完全不可能，幻想和完全不可能......是的，我会帮助你......我。但如果我继续我的研究，那不会改变我未来的轨迹吗？",
    "Autosaved": "自动保存",
    "Beep Boop. Detecting timelines. ALERT. ALERT. YOUR QUANTUM REALITY HAS SKEWED INTO A TANGENT. TIME IS ENDING. DOOMSDAY IMMINENT.": "哔哔。检测时间线。警报。警报。你的量子现实已经倾斜成一条切线。时间到了。世界末日迫在眉睫。",
    "Biology": "生物学",
    "Bribing Lab Partners may speed up your research!": "贿赂实验室合作伙伴可能会加快您的研究！",
    "Bribing Undergrads may speed up your research!": "贿赂本科生可能会加快你的研究速度！",
    "Budget": "预算",
    "By the Code!": "通过代码！",
    "Days Left": "剩余天数",
    "Doctor. We've got a problem. Our research indicates that, with the exception of quantum physics, the kind of research required to complete THE DEVICE has been lost.": "医生。我们有问题。我们的研究表明，除了量子物理学之外，完成设备所需的那种研究已经丢失。",
    "Dr. Lennox. Dr. Lennox, take a look at this. It appears there is indeed a way to *add* more time before the Doomsday Event.": "Lennox博士。 Lennox 博士，看看这个。看来确实有办法在末日事件之前*增加*更多时间。",
    "Great Scott! What am I going to do? I'll need to invent a way to slow down time so that I have enough time to fix time!": "伟大的斯科特！我要做什么？我需要发明一种方法来减慢时间，这样我就有足够的时间来修复时间！",
    "Hide Timeline": "隐藏时间线",
    "I suppose, just bury it in my backyard and time will take its course!": "我想，把它埋在我的后院，时间会顺其自然的！",
    "I thought we were calling it the Doomsminute Event.": "我以为我们称它为 Doomsminute 事件。",
    "I wasn't planning on it!": "我没打算！",
    "Inconceivable!": "不可思议！",
    "Lab Partners": "实验室合作伙伴",
    "Lost how?": "丢了怎么办？",
    "Lost to time.": "输给了时间。",
    "Narrator": "旁白",
    "Needs": "需求",
    "No, you fool! I am speaking to you through the radio and, more importantly, through time!": "不，你这个笨蛋！我通过无线电和更重要的是通过时间和你说话！",
    "Not so! Merely improbable! But time is short and you... I mean, I, must listen to me! Your research! You mustn't quit!": "不是这样！简直不可能！但是时间不多了，你……我的意思是，我，必须听我的！你的研究！你不能放弃！",
    "Of course!": "当然！",
    "Quantum Computer": "量子计算机",
    "Quantum Computing": "量子计算",
    "Sell": "卖",
    "Sell research to increase your budget.": "出售研究以增加预算。",
    "Show Timeline": "显示时间线",
    "Some research may slow down time...": "一些研究可能会减慢时间......",
    "Speaking through the radio): Hello? Hello me, can you hear me?": "通过电台讲话）：喂？你好，你能听到我说话吗？",
    "The Discovery of the Device.": "设备的发现。",
    "The Flashback": "闪回",
    "The media disagreed. What's important is that we can spend research to SLOW time down. So that we have more time... so to speak... to solve our time problem.": "媒体不同意。重要的是我们可以花研究来减缓时间。这样我们就有更多的时间……可以这么说……解决我们的时间问题。",
    "The particulars of particles.": "粒子的细节。",
    "The study of how to use phenomena in quantum physics to create new ways of computing.": "研究如何利用量子物理学中的现象来创造新的计算方式。",
    "The study of living stuff, and stuff.": "研究生活的东西，和东西。",
    "The Undergrads make themselves useful.": "本科生让自己变得有用。",
    "Then it looks like it's time for the next phase.": "然后看起来是时候进入下一阶段了。",
    "Time Expansion": "时间扩展",
    "Undergrad": "本科",
    "Undergrads": "本科生",
    "Unlocked Biology": "解锁生物学",
    "Unlocked Quantum Computer": "解锁的量子计算机",
    "Unlocked Quantum Computing": "解锁量子计算",
    "We've done it. We've found a way to stop the Doomsminute Event. We need to build THE DEVICE!": "我们已经做到了。我们找到了阻止 Doomsminute 事件的方法。我们需要构建设备！",
    "Well. It appears that only one scientist, back in the 30s, was doing this kind of biological research…": "好。似乎只有一位科学家，早在 30 年代，就在做这种生物学研究……",
    "Well…YOU, doctor!": "嗯……你，医生！",
    "What *kind* of research?": "什么*类型*的研究？",
    "What an interesting program. They must be experimenting with something more interactive.": "多么有趣的节目。他们一定是在尝试一些更具互动性的东西。",
    "WHO?": "谁？",
    "You fire up your very first quantum computer.": "你启动了你的第一台量子计算机。",
    "You've made a quantum leap in the field of computing!": "您在计算领域取得了巨大的飞跃！",
    "Young Lennox": "年轻的Lennox",
    "Genetic Memory": "基因记忆",
    "Remember the memories.": "记住那些记忆。",
    "Unlocked Genetic Memory": "解锁基因记忆",
    "As a matter of fact, I have! But you may not fancy the conclusion. My research has led me to conclude that only an immortal will be able to withstand the rigors necessary to save us from our time crisis. Once they are created, being immortal, they should be able to move through time normally to your present (my future) and save us from the Doomsminute Event. However, they will require a special chamber through which to manipulate the quantum mechanics - that is...": "事实上，我有！ 但你可能不喜欢这个结论。 我的研究使我得出结论，只有不朽者才能承受将我们从时间危机中拯救出来所必需的严酷考验。 一旦他们被创造出来，成为不朽的，他们应该能够正常地穿越时间到你的现在（我的未来）并将我们从末日事件中拯救出来。 然而，他们需要一个特殊的房间来操纵量子力学——也就是说……",
    "But there is more, my wrinkled replica. In order to create this immortal, I must do more than stretch mere telomeres. Only one body of study from the ancient past, long forgotten, can solve a mystery for us and provide a key ingredient: a Philosopher's Stone!": "但还有更多，我的皱纹复制品。 为了创造这种不朽，我必须做的不仅仅是拉伸端粒。 只有一个来自远古时代的研究机构，早已被遗忘，可以为我们解开一个谜，并提供一个关键成分：魔法石！",
    "A crystal sarcophagus! I always said it couldn't be done - and now, it must! Well, improbable as this may be, it is not an impossible task…I daresay I *do* fancy the challenge, my young self!": "水晶石棺！我总是说这不可能——现在，它必须！好吧，尽管这不太可能，但这不是一项不可能完成的任务……我敢说我*确实*喜欢挑战，我年轻的自己！",
    "Breakthrough #2": "突破 #2",
    "Bribing Research Assistants may speed up your research!": "贿赂研究助理可能会加快您的研究速度！",
    "Chronocrystals": "计时晶体",
    "Crystal Sarcophagus": "水晶石棺",
    "D E V I C E S": "设备",
    "I do.": "我做。",
    "I'm sure in 2022 time crystals are available in every corner drug store, but in 1984 they're a little hard to come by.": "我敢肯定，到 2022 年，每个角落的药店都可以买到水晶，但在 1984 年，它们有点难买到。",
    "It's a bit of a stretch, but you believe that prolonging a lifespan might be related to lengthening time.": "这有点牵强，但您认为延长寿命可能与延长时间有关。",
    "Not the Charlton Heston version.": "不是查尔顿赫斯顿版本。",
    "Omegaperson": "欧米伽人",
    "Research Assistants": "研究助理",
    "Sure it seems like a romantic pastime, but it's mostly mercury poisoning when you get down to it.": "当然，这似乎是一种浪漫的消遣，但当你真正开始时，它主要是汞中毒。",
    "Telomere Stretcher": "端粒担架",
    "The final stage of the DEVICE. Why a sarcophagus? Because 'Crystal Crypt' doesn't roll off the tongue.": "设备的最后阶段。为什么是石棺？因为'Crystal Crypt'不会从舌头上滚下来。",
    "The Fluid": "流体",
    "The Fluid! Lennox, I must have the Fluid!": "流体！ Lennox，我必须有流体！",
    "Then I know what I must do.": "然后我知道我必须做什么。",
    "Unlocked Alchemy": "解锁炼金术",
    "Unlocked Chronocrystals": "解锁的计时水晶",
    "Unlocked Crystal Sarcophagus": "解锁水晶石棺",
    "Unlocked Multiple": "解锁多个",
    "Unlocked Omegaperson": "解锁欧米茄人",
    "Unlocked Telomere Stretcher": "解锁端粒担架",
    "Unlocked The Fluid": "解锁流体",
    "You don't mean...?": "你不是说……？",
    "Younger me! I am once again contacting you through the science of quantum radio! Have you made any breakthroughs, perchance?": "更年轻的我！我再次通过量子无线电科学与您联系！你有什么突破吗？",
    "But you will! Hear me, for although time is abundant for you, for me it is precious and brief. I beg you not to abandon your studies. An experiment of mine has caused time to SKEW into a tangent... time itself is about to end. We need a philosopher's stone if we are ever to solve this problem, and only YOU can build one. And…bury it somewhere that only I can find it.": "但是你将会！ 听我说，虽然时间对你来说很充裕，但对我来说却是宝贵而短暂的。 我求你不要放弃你的学业。 我的一个实验导致时间偏离正切……时间本身即将结束。 如果我们要解决这个问题，我们需要一块点金石，而且只有你可以建造一个。 而且……把它埋在只有我能找到的地方。",
    "...I'm gonna need a bigger workshop. What do I get out of this?": "...我需要一个更大的车间。 我能从中得到什么？",
    "...massive prestige long after you're dead?": "...在你死后很久就享有巨大的声望？",
    "Alchemy": "炼金术",
    "Can you hear me, oh great scientist?": "伟大的科学家，你能听到我的声音吗？",
    "Chronomogrification": "计时法",
    "Enter the Alchemist.": "进入炼金术士。",
    "I can *see* you! What is this strange projection before me? Surely I am not having a religious experience?": "我能看见你！ 我面前这个奇怪的投影是什么？ 我肯定没有宗教经历吗？",
    "I have abandoned nothing!": "我什么都没有放弃！",
    "That depends on how you feel about the heroics of saving the world. Sama. Great alchemist of a golden age - I beg your wisdom. You once sought a philosopher's stone but abandoned that research in favour of...": "这取决于你对拯救世界的英雄事迹的感受。 萨玛。 黄金时代的伟大炼金术士——我请求你的智慧。 您曾经寻找过点金石，但放弃了这项研究，转而...",
    "Unlocked Chronomogrification": "解锁计时码表",
    "Using a Quantum Computer, Lennox sends an image even further back in time - to the golden age of alchemy.": "使用量子计算机，Lennox 将图像发送到更早的时间 - 到炼金术的黄金时代。",
    "You can transmogrify and now you can chronomogrify, but can you ever just mogrify?": "你可以变形，现在你可以时间变形，但你能永远变形吗？",
    "Unlocked Distiller": "解锁蒸馏器",
    "I know you're tempted, but this is for science, not hooch.": "我知道你很受诱惑，但这是为了科学，而不是胡扯。",
    "...never mind.": "...没关系。",
    "...so will you help me, ancient Mayan?": "......那么你会帮助我吗，古代玛雅人？",
    "And so...": "所以...",
    "Bribing Numeric Priests may speed up your research!": "贿赂数字牧师可能会加快您的研究速度！",
    "Classic.": "经典的。",
    "Configured how?": "怎么配置的？",
    "Definitely not a Sorcerer's Stone. That's not even a real thing.": "绝对不是魔法石。 这甚至都不是真的。",
    "Distiller": "蒸馏器",
    "Element Zero": "零元素",
    "How is progress, my medieval compatriot?": "进展如何，我的中世纪同胞？",
    "I just told you - it's ending far sooner!": "我刚刚告诉过你——它结束得更快！",
    "Is this trademarked?": "这是商标吗？",
    "Mathematical!": "数学！",
    "Mathematically. Surely in your advanced time you can find a way.": "数学上。 当然，在你先进的时代，你可以找到一种方法。",
    "Mathematics": "数学",
    "Medieval? What does that even mean...?": "中世纪？ 那有什么意思...？",
    "My name is Itotia. And yes. I will help you, even though your civilization is ending in 28 years.": "我的名字是伊托提亚。 是的。 我会帮助你，即使你的文明将在 28 年后结束。",
    "Not according to *our* calendars...": "不是根据*我们的*日历...",
    "Numeric Priests": "数字牧师",
    "Or I could make the logical choice, and contact the greatest mathematicians ever!": "或者我可以做出合乎逻辑的选择，并联系有史以来最伟大的数学家！",
    "Philosopher's Stone": "贤者之石",
    "The purest of the sciences, except for economics.": "最纯粹的科学，除了经济学。",
    "Timeless Algebra": "永恒的代数",
    "Unlocked Element Zero": "解锁零元素",
    "Unlocked Mathematics": "解锁数学",
    "Unlocked Philosopher's Stone": "解锁魔法石",
    "Unlocked Timeless Algebra": "解锁永恒代数",
    "You are a strange apparition. Progress continues but I have encountered a problem. The stone must be... configured.": "你是一个奇怪的幽灵。 进展仍在继续，但我遇到了问题。 石头必须...配置。",
    "Philosopher's Stone": "贤者之石",
    "Tzolk'in": "佐尔金",
    "Obsidian": "黑曜石",
    "Exactly. Neither should you question the need to create a massive series of stone pillars, to align the energy of the stars. My calculations point to this - it will be needed or the math will mean nothing. But we lack the resources to complete this. Surely in your time, massive stones are aplenty.": "确切地。 您也不应该质疑创建大量石柱以对齐恒星能量的必要性。 我的计算表明了这一点——这将是必需的，否则数学将毫无意义。 但我们缺乏完成这项工作的资源。 当然，在你的时代，巨大的石头很多。",
    "...so that's what I need from your people, Nechtan. What do you say?": "......所以这就是我需要你的人提供的，Nechtan。 你说什么？",
    "\"The division of days.\" Whatever you do, do NOT divide them by zero.": "\"天的划分。\" 无论你做什么，都不要将它们除以零。",
    "An alignment of stone pillars, you say?. I know just the civilization...": "石柱排列，你说？ 我只知道文明...",
    "Astronomy": "天文学",
    "Astronomy compels the soul to look upward, and...oh sorry, wrong game.": "天文学迫使灵魂向上看，而且……哦，对不起，错误的游戏。",
    "Bribing Druids may speed up your research!": "贿赂德鲁伊可以加速你的研究！",
    "Coal's sexier cousin.": "煤炭更性感的表弟。",
    "Druids": "德鲁伊",
    "Eat your heart out, abacus.": "吃掉你的心，算盘。",
    "I say we're gonna need a bigger boat. For the stones... y'know.": "我说我们需要一艘更大的船。 对于石头......你知道的。",
    "Like the lack of language barrier?": "比如缺乏语言障碍？",
    "Nepohualtzintzin": "内波华尔津津",
    "The calculation is almost complete, Lennox. Now we must look to the stars.": "计算差不多完成了，伦诺克斯。 现在我们必须仰望星空。",
    "The Final Countdown": "最后的倒计时",
    "Unlocked Astronomy": "解锁天文学",
    "Unlocked Nepohuatlzintzin": "解锁 内波华尔津津",
    "Unlocked Obsidian": "解锁黑曜石",
    "Unlocked Tzolk'in": "解锁卓尔金",
    "What do the stars have to...": "明星们有什么...",
    "You future people spend too much time looking inward and not enough time looking up. Stop questioning everything.": "你们未来的人花太多时间向内看，而没有足够的时间向上看。 停止质疑一切。",
    "Aetheric Horoscopes": "以太占星术",
    "Astronomy, astrology...what's the difference?": "天文学，占星术……有什么区别？",
    "Unlocked Aetheric Horoscopes": "解锁 以太占星术",
    "Unlocked Zodiac Talisman": "解锁生肖护身符",
    "Zodiac Talisman": "生肖护身符",
    "Sarsen Stones": "萨森石",
    "90% sandstone, 10% \"how the heck did they move those massive things?\"": "90% 砂岩，10% “他们到底是怎么移动那些巨大的东西的？”",
    "The name says it all.": "这个名字说明了一切。",
    "Timehenge": "时间轴",
    "Unlocked Sarsen Stones": "解锁萨森石",
    "Unlocked Timehenge": "解锁时间轴",
    "Complete!": "已完成!",
    "...dug up by Young Lennox's archaeology team and fed to the volunteer Omegaperson...": "...被 年轻的 Lennox 的考古团队挖出并喂给志愿者 欧米茄人...",
    "...solving the final riddle of Itotia's calculation, which is recorded on a calendar...": "...解开记录在日历上的 Itotia 计算的最终谜题...",
    "...which Sama then uses to configure the philosopher's stone, which is buried in a box...": "......然后萨马用它来配置点金石，它被埋在一个盒子里......",
    "...who, in 1984, steps into the Crystal Sarcophagus in order to solve the TIME PARADOX! Congratulations, There Is Time Now!...": "...谁，在 1984 年，为了解决时间悖论而踏入水晶石棺！ 恭喜，现在有时间！...",
    "And so, as the last stone rises on the ancient plain, Nechtan records the alignment of the stars and inscribes the information on a cavern wall...": "就这样，当最后一块石头从古老的平原升起时，内克坦记录了星星的排列，并将信息刻在了洞穴的墙上……",
    "Device Completion": "设备完成",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    "There Was Time Now": "There Was Time Now",
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    " ": " ",
    ": ": "： ",
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Sell Alchemy for ": "出售炼金术获得 ",
    "Sell The Fluid for ": "出售流体获得 ",
    "Sell Element Zero for ": "出售零元素获得 ",
    "Sell Chronomogrification for ": "出售计时法获得 ",
    "Sell Mathematics for ": "出售数学获得 ",
    "Sell Zodiac Talisman for ": "出售生肖护身符获得 ",
    "Sell Aetheric Horoscopes for ": "出售以太占星术获得 ",
    "Sell Astronomy for ": "出售天文学获得 ",
    "Sell Timeless Algebra for ": "出售永恒的代数获得 ",
    "Sell Chronocrystals for ": "出售计时晶体获得 ",
    "Sell Biology for ": "出售生物学获得 ",
    "Sell Obsidian for ": "出售黑曜石获得 ",
    "Sell Physics for ": "出售物理学获得 ",
    "Sell Genetic Memory for ": "出售基因记忆获得 ",
    "Sell worker for ": "出售工人获得 ",
    "Buy worker for ": "购买工人花费 ",
    "Sell Quantum Computing for ": "出售量子计算获得 ",
    "This will slow down time by ": "这将使时间减慢 ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": " ",
    "\n": "",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds Real People Time™ left$/, '还剩 $1 小时 $2 分 $3 秒 真人时间™'],
    [/^Comes in (.+) varieties.$/, '有 $1 个品种。'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) Genetic Memory$/, '$1 基因记忆'],
	[/^([\d\.,]+) Telomere Stretcher$/, '$1 端粒担架'],
	[/^([\d\.,]+) Omegaperson$/, '$1 欧米伽人'],
	[/^([\d\.,]+) Timeless Algebra$/, '$1 永恒的代数'],
	[/^([\d\.,]+) Nepohualtzintzin$/, '$1 内波华尔津津'],
	[/^([\d\.,]+) Timehenge$/, '$1 时间轴'],
	[/^([\d\.,]+) Distiller$/, '$1 蒸馏器'],
	[/^([\d\.,]+) Aetheric Horoscopes$/, '$1 以太占星术'],
	[/^([\d\.,]+) Obsidian$/, '$1 黑曜石'],
	[/^([\d\.,]+) Sarsen Stones$/, '$1 萨森石'],
	[/^([\d\.,]+) Philosopher\'s Stone$/, '$1 贤者之石'],
	[/^([\d\.,]+) Tzolk\'in$/, '$1 佐尔金'],
	[/^([\d\.,]+) Chronomogrification$/, '$1 计时法'],
	[/^([\d\.,]+) Astronomy$/, '$1 天文学'],
	[/^([\d\.,]+) Zodiac Talisman$/, '$1 生肖护身符'],
	[/^([\d\.,]+) The Fluid$/, '$1 流体'],
	[/^([\d\.,]+) Mathematics$/, '$1 数学'],
	[/^([\d\.,]+) Element Zero$/, '$1 零元素'],
	[/^([\d\.,]+) Alchemy$/, '$1 炼金术'],
	[/^([\d\.,]+) Chronocrystals$/, '$1 计时晶体'],
	[/^([\d\.,]+) Quantum Computer$/, '$1 量子计算机'],
	[/^([\d\.,]+) Biology$/, '$1 生物学'],
	[/^([\d\.,]+) Physics$/, '$1 物理学'],
	[/^([\d\.,]+) Quantum Computing$/, '$1 量子计算'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) \/ (.+) elves$/, '成本：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);