/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Click on a button to start researching!": "点击一个按钮开始研究！",
    "Intro": "介绍",
    "Let's get started...": "让我们开始吧...",
    "OK!": "好的!",
    "Physics": "物理学",
    "Research": "研究",
    "The year is 1984. You are Lennox, a physicist researching the most cutting-edge technology: Quantum Computing! With enough research, you should be able to build your own Quantum Computer.": "这一年是 1984 年。你是 Lennox，一位研究最前沿技术：量子计算 的物理学家！ 通过足够的研究，您应该能够构建自己的量子计算机。",
    "About": "关于",
    "Light Mode": "浅色模式",
    "Restart": "重新开始",
    "Version History": "更新日志",
    "Cancel": "取消",
    "copy export to clipboard": "复制存档到剪切板",
    "Dark Mode": "深色模式",
    "Copy to Clipboard": "复制到剪切板",
    "Done!": "完成!",
    "Export Game": "导出存档",
    "Back to it!": "返回！",
    "author page": "作者页面",
    "made for the new year's incremental game jam (2022)": "为新年的增量游戏 jam 制作(2022)",
    "Neat": "关闭",
    "Pause": "暂停",
    "Paused": "已暂停",
    "special thanks to": "特别的感谢给",
    "There was time now... to go to the bathroom.": "现在有时间……去洗手间了。",
    "this is a game about \"science\" and \"time\"": "这是一个关于“科学”和“时间”的游戏",
    "writing by James Funfer": "作者是 James Funfer",
    "I'm going back to the start": "我要回到起点",
    "Oops, never mind": "喔，没关系",
    "Restart Game?": "重新开始游戏？",
    "You will lose all of your progress!": "你将失去所有的游戏进度！建议先导出、备份存档~",
    "...how?": "...如何？",
    "...let's not overthink this. Just carry on with your research and forward me the data.": "...我们不要想太多。 继续你的研究并将数据转发给我。",
    "A Breakthrough.": "一个突破。",
    "Eureka! If I reroute the nanoseconds through the quantum flux thingamajig in the compumatrix, I *should* be able to slow time down. If only I had some undergrads to help, this is a lot of work and I haven't even had time to order a pizza - the most important element of research!": "尤里卡！ 如果我通过计算矩阵中的量子通量 thingamajig 重新路由纳秒，我*应该*能够减慢时间。 如果我有一些本科生可以帮忙，这是很多工作，我什至没有时间点一份披萨——这是研究中最重要的元素！",
    "Yes you are! In approximately three days you will lose most of your funding. But you must carry on! I am you from the future and I come with a dire warning... a quantum doomsday event is coming and I need your assistance to stop it... will you help me?": "是的，你是！ 在大约三天内，您将失去大部分资金。 但你必须继续！ 我是来自未来的你，我带着可怕的警告而来……量子世界末日事件即将来临，我需要你的帮助来阻止它……你能帮帮我吗？",
    "Yessirma'am, it is indeed an ordinary type day in the ordinary present in which I do my EXTRAORDINARY RESEARCH. It sure is quiet and lonely doing research of the singularly unique type to which I am accustomed to doing. Maybe the radio will help motivate me to greater heights of genius...": "Yessirma'am，这确实是一个平凡的日子，我做我的非凡研究。 做我习惯做的独特类型的研究肯定是安静而孤独的。 也许收音机会帮助激励我达到更高的天才高度……",
    "And it was at that time that Lennox experienced a *flashback*": "正是在那个时候，Lennox经历了一次*闪回*",
    "And then, as Young Lennox fiddled with the radio dial...": "然后，当年轻的Lennox摆弄收音机拨号时……",
    "As completely improbable, fantastical, and downright impossible as this all sounds... yes, I will help you... me. But if I continue my research, won't that change the trajectory of my future?": "就像这一切听起来一样完全不可能，幻想和完全不可能......是的，我会帮助你......我。但如果我继续我的研究，那不会改变我未来的轨迹吗？",
    "Autosaved": "自动保存",
    "Beep Boop. Detecting timelines. ALERT. ALERT. YOUR QUANTUM REALITY HAS SKEWED INTO A TANGENT. TIME IS ENDING. DOOMSDAY IMMINENT.": "哔哔。检测时间线。警报。警报。你的量子现实已经倾斜成一条切线。时间到了。世界末日迫在眉睫。",
    "Biology": "生物学",
    "Bribing Lab Partners may speed up your research!": "贿赂实验室合作伙伴可能会加快您的研究！",
    "Bribing Undergrads may speed up your research!": "贿赂本科生可能会加快你的研究速度！",
    "Budget": "预算",
    "By the Code!": "通过代码！",
    "Days Left": "剩余天数",
    "Doctor. We've got a problem. Our research indicates that, with the exception of quantum physics, the kind of research required to complete THE DEVICE has been lost.": "医生。我们有问题。我们的研究表明，除了量子物理学之外，完成设备所需的那种研究已经丢失。",
    "Dr. Lennox. Dr. Lennox, take a look at this. It appears there is indeed a way to *add* more time before the Doomsday Event.": "Lennox博士。 Lennox 博士，看看这个。看来确实有办法在末日事件之前*增加*更多时间。",
    "Great Scott! What am I going to do? I'll need to invent a way to slow down time so that I have enough time to fix time!": "伟大的斯科特！我要做什么？我需要发明一种方法来减慢时间，这样我就有足够的时间来修复时间！",
    "Hide Timeline": "隐藏时间线",
    "I suppose, just bury it in my backyard and time will take its course!": "我想，把它埋在我的后院，时间会顺其自然的！",
    "I thought we were calling it the Doomsminute Event.": "我以为我们称它为 Doomsminute 事件。",
    "I wasn't planning on it!": "我没打算！",
    "Inconceivable!": "不可思议！",
    "Lab Partners": "实验室合作伙伴",
    "Lost how?": "丢了怎么办？",
    "Lost to time.": "输给了时间。",
    "Narrator": "旁白",
    "Needs": "需求",
    "No, you fool! I am speaking to you through the radio and, more importantly, through time!": "不，你这个笨蛋！我通过无线电和更重要的是通过时间和你说话！",
    "Not so! Merely improbable! But time is short and you... I mean, I, must listen to me! Your research! You mustn't quit!": "不是这样！简直不可能！但是时间不多了，你……我的意思是，我，必须听我的！你的研究！你不能放弃！",
    "Of course!": "当然！",
    "Quantum Computer": "量子计算机",
    "Quantum Computing": "量子计算",
    "Sell": "卖",
    "Sell research to increase your budget.": "出售研究以增加预算。",
    "Show Timeline": "显示时间线",
    "Some research may slow down time...": "一些研究可能会减慢时间......",
    "Speaking through the radio): Hello? Hello me, can you hear me?": "通过电台讲话）：喂？你好，你能听到我说话吗？",
    "The Discovery of the Device.": "设备的发现。",
    "The Flashback": "闪回",
    "The media disagreed. What's important is that we can spend research to SLOW time down. So that we have more time... so to speak... to solve our time problem.": "媒体不同意。重要的是我们可以花研究来减缓时间。这样我们就有更多的时间……可以这么说……解决我们的时间问题。",
    "The particulars of particles.": "粒子的细节。",
    "The study of how to use phenomena in quantum physics to create new ways of computing.": "研究如何利用量子物理学中的现象来创造新的计算方式。",
    "The study of living stuff, and stuff.": "研究生活的东西，和东西。",
    "The Undergrads make themselves useful.": "本科生让自己变得有用。",
    "Then it looks like it's time for the next phase.": "然后看起来是时候进入下一阶段了。",
    "There Was Time Now": "现在有时间",
    "Time Expansion": "时间扩展",
    "Undergrad": "本科",
    "Undergrads": "本科生",
    "Unlocked Biology": "解锁生物学",
    "Unlocked Quantum Computer": "解锁的量子计算机",
    "Unlocked Quantum Computing": "解锁量子计算",
    "We've done it. We've found a way to stop the Doomsminute Event. We need to build THE DEVICE!": "我们已经做到了。我们找到了阻止 Doomsminute 事件的方法。我们需要构建设备！",
    "Well. It appears that only one scientist, back in the 30s, was doing this kind of biological research…": "好。似乎只有一位科学家，早在 30 年代，就在做这种生物学研究……",
    "Well…YOU, doctor!": "嗯……你，医生！",
    "What *kind* of research?": "什么*类型*的研究？",
    "What an interesting program. They must be experimenting with something more interactive.": "多么有趣的节目。他们一定是在尝试一些更具互动性的东西。",
    "WHO?": "谁？",
    "You fire up your very first quantum computer.": "你启动了你的第一台量子计算机。",
    "You've made a quantum leap in the field of computing!": "您在计算领域取得了巨大的飞跃！",
    "Young Lennox": "年轻的Lennox",
    "Genetic Memory": "基因记忆",
    "Remember the memories.": "记住那些记忆。",
    "Unlocked Genetic Memory": "解锁基因记忆",
    "As a matter of fact, I have! But you may not fancy the conclusion. My research has led me to conclude that only an immortal will be able to withstand the rigors necessary to save us from our time crisis. Once they are created, being immortal, they should be able to move through time normally to your present (my future) and save us from the Doomsminute Event. However, they will require a special chamber through which to manipulate the quantum mechanics - that is...": "事实上，我有！ 但你可能不喜欢这个结论。 我的研究使我得出结论，只有不朽者才能承受将我们从时间危机中拯救出来所必需的严酷考验。 一旦他们被创造出来，成为不朽的，他们应该能够正常地穿越时间到你的现在（我的未来）并将我们从末日事件中拯救出来。 然而，他们需要一个特殊的房间来操纵量子力学——也就是说……",
    "But there is more, my wrinkled replica. In order to create this immortal, I must do more than stretch mere telomeres. Only one body of study from the ancient past, long forgotten, can solve a mystery for us and provide a key ingredient: a Philosopher's Stone!": "但还有更多，我的皱纹复制品。 为了创造这种不朽，我必须做的不仅仅是拉伸端粒。 只有一个来自远古时代的研究机构，早已被遗忘，可以为我们解开一个谜，并提供一个关键成分：魔法石！",
    "A crystal sarcophagus! I always said it couldn't be done - and now, it must! Well, improbable as this may be, it is not an impossible task…I daresay I *do* fancy the challenge, my young self!": "水晶石棺！我总是说这不可能——现在，它必须！好吧，尽管这不太可能，但这不是一项不可能完成的任务……我敢说我*确实*喜欢挑战，我年轻的自己！",
    "Breakthrough #2": "突破 #2",
    "Bribing Research Assistants may speed up your research!": "贿赂研究助理可能会加快您的研究速度！",
    "Chronocrystals": "计时晶体",
    "Crystal Sarcophagus": "水晶石棺",
    "D E V I C E S": "设备",
    "I do.": "我做。",
    "I'm sure in 2022 time crystals are available in every corner drug store, but in 1984 they're a little hard to come by.": "我敢肯定，到 2022 年，每个角落的药店都可以买到水晶，但在 1984 年，它们有点难买到。",
    "It's a bit of a stretch, but you believe that prolonging a lifespan might be related to lengthening time.": "这有点牵强，但您认为延长寿命可能与延长时间有关。",
    "Not the Charlton Heston version.": "不是查尔顿赫斯顿版本。",
    "Omegaperson": "欧米茄人",
    "Research Assistants": "研究助理",
    "Sure it seems like a romantic pastime, but it's mostly mercury poisoning when you get down to it.": "当然，这似乎是一种浪漫的消遣，但当你真正开始时，它主要是汞中毒。",
    "Telomere Stretcher": "端粒担架",
    "The final stage of the DEVICE. Why a sarcophagus? Because 'Crystal Crypt' doesn't roll off the tongue.": "设备的最后阶段。为什么是石棺？因为'Crystal Crypt'不会从舌头上滚下来。",
    "The Fluid": "流体",
    "The Fluid! Lennox, I must have the Fluid!": "流体！ Lennox，我必须有流体！",
    "Then I know what I must do.": "然后我知道我必须做什么。",
    "Unlocked Alchemy": "解锁炼金术",
    "Unlocked Chronocrystals": "解锁的计时水晶",
    "Unlocked Crystal Sarcophagus": "解锁水晶石棺",
    "Unlocked Multiple": "解锁多个",
    "Unlocked Omegaperson": "解锁欧米茄人",
    "Unlocked Telomere Stretcher": "解锁端粒担架",
    "Unlocked The Fluid": "解锁流体",
    "You don't mean...?": "你不是说……？",
    "Younger me! I am once again contacting you through the science of quantum radio! Have you made any breakthroughs, perchance?": "更年轻的我！我再次通过量子无线电科学与您联系！你有什么突破吗？",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    " ": " ",
    ": ": "： ",
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Sell Biology for ": "出售生物学获得 ",
    "Sell Physics for ": "出售物理学获得 ",
    "Sell Genetic Memory for ": "出售基因记忆获得 ",
    "Sell worker for ": "出售工人获得 ",
    "Buy worker for ": "购买工人花费 ",
    "Sell Quantum Computing for ": "出售量子计算获得 ",
    "This will slow down time by ": "这将使时间减慢 ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": " ",
    "\n": "",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) Genetic Memory$/, '$1 基因记忆'],
	[/^([\d\.,]+) Telomere Stretcher$/, '$1 端粒担架'],
	[/^([\d\.,]+) Biology$/, '$1 生物学'],
	[/^([\d\.,]+) Physics$/, '$1 物理学'],
	[/^([\d\.,]+) Quantum Computing$/, '$1 量子计算'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) \/ (.+) elves$/, '成本：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);